

/******************************************
 * Auto-generated by CodeRocket
 * 24.11.2008 16:16:59
 ******************************************/
using System;
using System.Data;
using System.Xml.Serialization;
using KnowledgeBase.BussinesLayer.Core;
using KnowledgeBase.DAL;
using Savchin.Validation;


namespace KnowledgeBase.BussinesLayer
{

    /// <summary>
    /// Base FileInclude
    /// </summary>
    [Serializable]
    public class FileInclude : EntityBase<FileIncludeValue>, IFile
    {



        #region Properties


        /// <summary>
        /// Gets or sets the FileIncludeID.
        /// </summary>
        /// <value>The FileIncludeID.</value>   
        [XmlAttribute]
        public System.Guid FileIncludeID
        {
            get { return ObjectValue.FileIncludeID; }
            set { ObjectValue.FileIncludeID = value; }
        }

        /// <summary>
        /// Gets or sets the FileName.
        /// </summary>
        /// <value>The FileName.</value>   
        [XmlAttribute]
        [RequiredFieldValidation()]
        public System.String FileName
        {
            get { return ObjectValue.FileName; }
            set { ObjectValue.FileName = value; }
        }

        /// <summary>
        /// Gets or sets the KnowledgeID.
        /// </summary>
        /// <value>The KnowledgeID.</value>   
        [XmlAttribute]
        public System.Int32 KnowledgeID
        {
            get { return ObjectValue.KnowledgeID; }
            set { ObjectValue.KnowledgeID = value; }
        }

        /// <summary>
        /// Gets or sets the Size.
        /// </summary>
        /// <value>The Size.</value>   
        [XmlAttribute]
        public System.Int32 Size
        {
            get { return ObjectValue.Size; }
            set { ObjectValue.Size = value; }
        }

        /// <summary>
        /// Gets the ID.
        /// </summary>
        /// <value>The ID.</value>
        public object ID
        {
            get { return FileIncludeID; }
        }
        /// <summary>
        /// Gets the query string.
        /// </summary>
        /// <value>The query string.</value>
        public string QueryString
        {
            get { return string.Format("ID={0}", FileIncludeID.ToString().Replace("-", string.Empty)); }
        }

        #endregion

        /// <summary>
        /// Initializes a new instance of the <see cref="FileInclude"/> class.
        /// </summary>
        public FileInclude()
            : base()
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="FileInclude"/> class.
        /// </summary>
        /// <param name="value">The value.</param>
        internal FileInclude(FileIncludeValue value)
            : base(value)
        {
        }


        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        //        protected override void Copy(object destination)
        //        {
        //            FileIncludeBase<TPool> dest = destination as FileIncludeBase<TPool>;

        //           dest._FileIncludeID = _FileIncludeID;
        //           dest._FileName = _FileName;
        //           dest._KnowledgeID = _KnowledgeID;
        //           dest._Size = _Size;

        //            base.Copy(destination);
        //       }	







    }
}
