

/******************************************
 * Auto-generated by CodeRocket
 * 09.05.2008 10:56:23
 ******************************************/
using System;
using System.Xml.Serialization;
using KnowledgeBase.BussinesLayer.Core;
using KnowledgeBase.BussinesLayer.Security;
using KnowledgeBase.DAL;
using Savchin.Text;
using Savchin.Validation;

namespace KnowledgeBase.BussinesLayer
{

    /// <summary>
    /// Base User
    /// </summary>
    [Serializable]
    public class User : EntityBase<UserValue>
    {



        #region Properties
        /// <summary>
        /// Gets the full name.
        /// </summary>
        /// <value>The full name.</value>
        [XmlIgnore]
        public string FullName
        {
            get { return (string.IsNullOrEmpty(LastName)) ? FirstName : LastName + " " + FirstName; }
        }

        /// <summary>
        /// Gets or sets the CreationDate.
        /// </summary>
        /// <value>The CreationDate.</value>   
        [XmlElement(ElementName = "CreationDate")]
        public DateTime CreationDate
        {
            get { return ObjectValue.CreationDate; }
            set { ObjectValue.CreationDate = value; }
        }

        /// <summary>
        /// Gets or sets the Email.
        /// </summary>
        /// <value>The Email.</value>   
        [XmlElement(ElementName = "Email")]
        [RequiredFieldValidation]
        [RegularExpressionValidation(RegularExpressions.Email)]
        public String Email
        {
            get { return ObjectValue.Email; }
            set { ObjectValue.Email = value; }
        }

        /// <summary>
        /// Gets or sets the FirstName.
        /// </summary>
        /// <value>The FirstName.</value>   
        [XmlElement(ElementName = "FirstName")]
        public String FirstName
        {
            get { return ObjectValue.FirstName; }
            set { ObjectValue.FirstName = value; }
        }

        /// <summary>
        /// Gets or sets the LastName.
        /// </summary>
        /// <value>The LastName.</value>   
        [XmlElement(ElementName = "LastName")]
        public String LastName
        {
            get { return ObjectValue.LastName; }
            set { ObjectValue.LastName = value; }
        }

        /// <summary>
        /// Gets or sets the Login.
        /// </summary>
        /// <value>The Login.</value>   
        [XmlElement(ElementName = "Login")]
        [RequiredFieldValidation]
        public String Login
        {
            get { return ObjectValue.Login; }
            set { ObjectValue.Login = value; }
        }

        /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        /// <value>The Password.</value>   
        [XmlElement(ElementName = "Password")]
        [RequiredFieldValidation]
        public String Password
        {
            get { return ObjectValue.Password; }
            set { ObjectValue.Password = value; }
        }

        /// <summary>
        /// Gets or sets the SecurityAnswer.
        /// </summary>
        /// <value>The SecurityAnswer.</value>   
        [XmlElement(ElementName = "SecurityAnswer")]
        public String SecurityAnswer
        {
            get { return ObjectValue.SecurityAnswer; }
            set { ObjectValue.SecurityAnswer = value; }
        }

        /// <summary>
        /// Gets or sets the SecurityQuestion.
        /// </summary>
        /// <value>The SecurityQuestion.</value>   
        [XmlElement(ElementName = "SecurityQuestion")]
        public String SecurityQuestion
        {
            get { return ObjectValue.SecurityQuestion; }
            set { ObjectValue.SecurityQuestion = value; }
        }

        /// <summary>
        /// Gets or sets the UserID.
        /// </summary>
        /// <value>The UserID.</value>   
        [XmlElement(ElementName = "UserID")]
        public Int32 UserID
        {
            get { return ObjectValue.UserID; }
            set { ObjectValue.UserID = value; }
        }

        /// <summary>
        /// Gets or sets the root permission.
        /// </summary>
        /// <value>The root permission.</value>
        [XmlElement(ElementName = "RootPermission")]
        public Permission? RootPermission
        {
            get { return (Permission?)ObjectValue.RootPermissionID; }
            set { ObjectValue.RootPermissionID = (short?)value; }
        }


        /// <summary>
        /// Gets a value indicating whether this instance is  adminitrator of users and theirs rights.
        /// </summary>
        /// <value>
        /// 	<c>true</c> if this instance is user admin; otherwise, <c>false</c>.
        /// </value>
        public bool IsUserAdmin
        {
            get { return ObjectValue.IsUserAdmin; }
        }

        /// <summary>
        /// Gets a value indicating whether this instance is system.
        /// </summary>
        /// <value><c>true</c> if this instance is system; otherwise, <c>false</c>.</value>
        public bool IsSystem
        {
            get { return ObjectValue.IsSystem; }
        }
        #endregion


        /// <summary>
        /// Called when [end edit].
        /// </summary>
        protected override void OnEndEdit()
        {
            base.OnEndEdit();

            Context.ManagerUser.Save(this);
        }

  



    }
}
