

/******************************************
 * Auto-generated by CodeRocket
 * 24.11.2008 16:17:00
 ******************************************/
using System;
using System.Data;
using System.Xml.Serialization;
using KnowledgeBase.BussinesLayer.Core;
using KnowledgeBase.DAL;
using Savchin.Validation;


namespace KnowledgeBase.BussinesLayer
{

    /// <summary>
    /// Base UserFile
    /// </summary>
    [Serializable]
    public class UserFile : EntityBase<UserFileValue>, IFile
    {



        #region Properties


        /// <summary>
        /// Gets or sets the FileName.
        /// </summary>
        /// <value>The FileName.</value>   
        [XmlAttribute]
        [RequiredFieldValidation()]
        public System.String FileName
        {
            get { return ObjectValue.FileName; }
            set { ObjectValue.FileName = value; }
        }

        /// <summary>
        /// Gets or sets the Size.
        /// </summary>
        /// <value>The Size.</value>   
        [XmlAttribute]
        public System.Int32 Size
        {
            get { return ObjectValue.Size; }
            set { ObjectValue.Size = value; }
        }

        /// <summary>
        /// Gets the query string.
        /// </summary>
        /// <value>The query string.</value>
        public string QueryString
        {
            get { return string.Format("UserFileID={0}", UserFileID); }
        }

        /// <summary>
        /// Gets the ID.
        /// </summary>
        /// <value>The ID.</value>
        public object ID
        {
            get { return UserFileID;  }
        }

        /// <summary>
        /// Gets or sets the UserFileID.
        /// </summary>
        /// <value>The UserFileID.</value>   
        [XmlAttribute]
        public System.Int32 UserFileID
        {
            get { return ObjectValue.UserFileID; }
            set { ObjectValue.UserFileID = value; }
        }

        /// <summary>
        /// Gets or sets the UserID.
        /// </summary>
        /// <value>The UserID.</value>   
        [XmlAttribute]
        public System.Int32 UserID
        {
            get { return ObjectValue.UserID; }
            set { ObjectValue.UserID = value; }
        }

        #endregion

        /// <summary>
        /// Initializes a new instance of the <see cref="UserFile"/> class.
        /// </summary>
        public UserFile()
            : base()
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserFile"/> class.
        /// </summary>
        /// <param name="value">The value.</param>
        internal UserFile(UserFileValue value)
            : base(value)
        {
        }


        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        //        protected override void Copy(object destination)
        //        {
        //            UserFileBase<TPool> dest = destination as UserFileBase<TPool>;

        //           dest._FileName = _FileName;
        //           dest._Size = _Size;
        //           dest._UserFileID = _UserFileID;
        //           dest._UserID = _UserID;

        //            base.Copy(destination);
        //       }	







    }
}
