

/******************************************
 * Auto-generated by CodeRocket
 * 08.11.2009 9:14:29
 ******************************************/
using System;
using System.Xml.Serialization;
using Savchin.Validation;
using Site.Core;
using Site.Dal.Entities;


namespace Site.Bl 
{    
    
	/// <summary>
	/// Base Product
	/// </summary>
	[Serializable]
	public class Product : EntityBase<ProductValue>
{

     	
	
	 #region Properties

        
              /// <summary>
        /// Gets or sets the CreationDate.
        /// </summary>
        /// <value>The CreationDate.</value>   
		[XmlAttribute]
  		public System.DateTime CreationDate 
		{
			get{return objectValue.CreationDate;}
			set{objectValue.CreationDate = value;}
		}			

              /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        /// <value>The Name.</value>   
		[XmlAttribute]
        [RequiredFieldValidation()]
  		public System.String Name 
		{
			get{return objectValue.Name;}
			set{objectValue.Name = value;}
		}			

              /// <summary>
        /// Gets or sets the PrivateKey.
        /// </summary>
        /// <value>The PrivateKey.</value>   
		[XmlAttribute]
  		public System.Byte[] PrivateKey 
		{
			get{return objectValue.PrivateKey;}
			set{objectValue.PrivateKey = value;}
		}			

              /// <summary>
        /// Gets or sets the ProductID.
        /// </summary>
        /// <value>The ProductID.</value>   
		[XmlAttribute]
  		public System.Int32 ProductID 
		{
			get{return objectValue.ProductID;}
			set{objectValue.ProductID = value;}
		}			

              /// <summary>
        /// Gets or sets the PublicKey.
        /// </summary>
        /// <value>The PublicKey.</value>   
		[XmlAttribute]
  		public System.Byte[] PublicKey 
		{
			get{return objectValue.PublicKey;}
			set{objectValue.PublicKey = value;}
		}			

        
        #endregion
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Product"/> class.
        /// </summary>
        public Product() : base()
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="Product"/> class.
        /// </summary>
        /// <param name="value">The value.</param>
        internal Product(ProductValue value) : base(value)
        {
        }       
          
        
        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
//        protected override void Copy(object destination)
//        {
//            ProductBase<TPool> dest = destination as ProductBase<TPool>;
            
 //           dest._CreationDate = _CreationDate;
 //           dest._Name = _Name;
 //           dest._PrivateKey = _PrivateKey;
 //           dest._ProductID = _ProductID;
 //           dest._PublicKey = _PublicKey;
            
 //            base.Copy(destination);
 //       }	
        
        

        
        
 
 
	}
}
