

/******************************************
 * Auto-generated by CodeRocket
 * 07.11.2009 22:52:52
 ******************************************/
using System;
using System.Xml.Serialization;
using Savchin.Validation;
using Site.Core;
using Site.Dal.Entities;


namespace Site.Bl 
{    
    
	/// <summary>
	/// Base Transfer
	/// </summary>
	[Serializable]
	public class Transfer : EntityBase<TransferValue>
{

     	
	
	 #region Properties

        
              /// <summary>
        /// Gets or sets the Ammount.
        /// </summary>
        /// <value>The Ammount.</value>   
		[XmlAttribute]
  		public System.Decimal Ammount 
		{
			get{return objectValue.Ammount;}
			set{objectValue.Ammount = value;}
		}			

              /// <summary>
        /// Gets or sets the Date.
        /// </summary>
        /// <value>The Date.</value>   
		[XmlAttribute]
  		public System.DateTime Date 
		{
			get{return objectValue.Date;}
			set{objectValue.Date = value;}
		}			

              /// <summary>
        /// Gets or sets the Description.
        /// </summary>
        /// <value>The Description.</value>   
		[XmlAttribute]
  		public System.String Description 
		{
			get{return objectValue.Description;}
			set{objectValue.Description = value;}
		}			

              /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>   
		[XmlAttribute]
  		public System.Int32 ID 
		{
			get{return objectValue.ID;}
			set{objectValue.ID = value;}
		}			

              /// <summary>
        /// Gets or sets the InvoiceId.
        /// </summary>
        /// <value>The InvoiceId.</value>   
		[XmlAttribute]
  		public System.Int32? InvoiceId 
		{
			get{return objectValue.InvoiceId;}
			set{objectValue.InvoiceId = value;}
		}			

              /// <summary>
        /// Gets or sets the Purse.
        /// </summary>
        /// <value>The Purse.</value>   
		[XmlAttribute]
        [RequiredFieldValidation()]
  		public System.String Purse 
		{
			get{return objectValue.Purse;}
			set{objectValue.Purse = value;}
		}			

              /// <summary>
        /// Gets or sets the TransferId.
        /// </summary>
        /// <value>The TransferId.</value>   
		[XmlAttribute]
  		public System.Int32? TransferId 
		{
			get{return objectValue.TransferId;}
			set{objectValue.TransferId = value;}
		}			

        
        #endregion
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Transfer"/> class.
        /// </summary>
        public Transfer() : base()
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="Transfer"/> class.
        /// </summary>
        /// <param name="value">The value.</param>
        internal Transfer(TransferValue value) : base(value)
        {
        }       
          
        
        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
//        protected override void Copy(object destination)
//        {
//            TransferBase<TPool> dest = destination as TransferBase<TPool>;
            
 //           dest._Ammount = _Ammount;
 //           dest._Date = _Date;
 //           dest._Description = _Description;
 //           dest._ID = _ID;
 //           dest._InvoiceId = _InvoiceId;
 //           dest._Purse = _Purse;
 //           dest._TransferId = _TransferId;
            
 //            base.Copy(destination);
 //       }	
        
        

        
        
 
 
	}
}
