

/******************************************
 * Auto-generated by CodeRocket
 * 08.11.2009 10:08:00
 ******************************************/
using System;
using System.Xml.Serialization;
using Savchin.ComponentModel;
using Savchin.Text;
using Savchin.Validation;
using Site.Core;
using Site.Dal.Entities;


namespace Site.Bl
{

    /// <summary>
    /// Base User
    /// </summary>
    [Serializable]
    public class User : EntityBase<UserValue>
    {



        #region Properties


        /// <summary>
        /// Gets or sets the CreationDate.
        /// </summary>
        /// <value>The CreationDate.</value>   
        [XmlAttribute]
        public System.DateTime CreationDate
        {
            get { return objectValue.CreationDate; }
            set { objectValue.CreationDate = value; }
        }

        /// <summary>
        /// Gets or sets the Email.
        /// </summary>
        /// <value>The Email.</value>   
        [XmlAttribute]
        [RequiredFieldValidation()]
        [RegularExpressionValidation(RegularExpressions.Email)]
        public System.String Email
        {
            get { return objectValue.Email; }
            set { objectValue.Email = value; }
        }

        /// <summary>
        /// Gets or sets the FirstName.
        /// </summary>
        /// <value>The FirstName.</value>   
        [XmlAttribute]
        [RequiredFieldValidation()]
        [DisplayNameEx("Site.Bl.Resource, Site.Core", "pFirstName")]
        public System.String FirstName
        {
            get { return objectValue.FirstName; }
            set { objectValue.FirstName = value; }
        }

        /// <summary>
        /// Gets or sets the IsAdmin.
        /// </summary>
        /// <value>The IsAdmin.</value>   
        [XmlAttribute]
        public System.Boolean IsAdmin
        {
            get { return objectValue.IsAdmin; }
            set { objectValue.IsAdmin = value; }
        }

        /// <summary>
        /// Gets or sets the LastName.
        /// </summary>
        /// <value>The LastName.</value>   
        [XmlAttribute]
        [RequiredFieldValidation()]
        [DisplayNameEx("Site.Bl.Resource, Site.Core", "pLastName")]
        public System.String LastName
        {
            get { return objectValue.LastName; }
            set { objectValue.LastName = value; }
        }

        /// <summary>
        /// Gets or sets the Login.
        /// </summary>
        /// <value>The Login.</value>   
        [XmlAttribute]
        [RequiredFieldValidation()]
        [DisplayNameEx("Site.Bl.Resource, Site.Core", "pLogin")]
        public System.String Login
        {
            get { return objectValue.Login; }
            set { objectValue.Login = value; }
        }

        /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        /// <value>The Password.</value>   
        [XmlAttribute]
        [RequiredFieldValidation()]
        [DisplayNameEx("Site.Bl.Resource, Site.Core", "pPassword")]
        public System.String Password
        {
            get { return objectValue.Password; }
            set { objectValue.Password = value; }
        }

        /// <summary>
        /// Gets or sets the SecurityAnswer.
        /// </summary>
        /// <value>The SecurityAnswer.</value>   
        [XmlAttribute]
        [RequiredFieldValidation()]
        [DisplayNameEx("Site.Bl.Resource, Site.Core", "pSecurityAnswer")]
        public System.String SecurityAnswer
        {
            get { return objectValue.SecurityAnswer; }
            set { objectValue.SecurityAnswer = value; }
        }

        /// <summary>
        /// Gets or sets the SecurityQuestion.
        /// </summary>
        /// <value>The SecurityQuestion.</value>   
        [XmlAttribute]
        [RequiredFieldValidation()]
        [DisplayNameEx("Site.Bl.Resource, Site.Core", "pSecurityQuestion")]
        public System.String SecurityQuestion
        {
            get { return objectValue.SecurityQuestion; }
            set { objectValue.SecurityQuestion = value; }
        }

        /// <summary>
        /// Gets or sets the UserID.
        /// </summary>
        /// <value>The UserID.</value>   
        [XmlAttribute]
        public System.Int32 UserID
        {
            get { return objectValue.UserID; }
            set { objectValue.UserID = value; }
        }


        #endregion

        /// <summary>
        /// Initializes a new instance of the <see cref="User"/> class.
        /// </summary>
        public User()
            : base()
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="User"/> class.
        /// </summary>
        /// <param name="value">The value.</param>
        internal User(UserValue value)
            : base(value)
        {
          
        }


        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        //        protected override void Copy(object destination)
        //        {
        //            UserBase<TPool> dest = destination as UserBase<TPool>;

        //           dest._CreationDate = _CreationDate;
        //           dest._Email = _Email;
        //           dest._FirstName = _FirstName;
        //           dest._IsAdmin = _IsAdmin;
        //           dest._LastName = _LastName;
        //           dest._Login = _Login;
        //           dest._Password = _Password;
        //           dest._SecurityAnswer = _SecurityAnswer;
        //           dest._SecurityQuestion = _SecurityQuestion;
        //           dest._UserID = _UserID;

        //            base.Copy(destination);
        //       }	







    }
}
