/******************************************
 * Auto-generated by CodeRocket
 * 24.11.2008 16:16:01
 ******************************************/
using System;
using Savchin.Core;


namespace KnowledgeBase.DAL
{

    /// <summary>
    /// FileInclude Value object
    /// </summary>
    [Serializable]
    public class FileIncludeValue : ICopiable
    {

        public System.Guid FileIncludeID;
        public System.String FileName;
        public System.Int32 KnowledgeID;
        public System.Int32 Size;




        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        public void Copy(object destination)
        {

            FileIncludeValue dest = destination as FileIncludeValue;
            if (dest == null)
                return;
            dest.FileIncludeID = FileIncludeID;
            dest.FileName = FileName;
            dest.KnowledgeID = KnowledgeID;
            dest.Size = Size;


        }







    }
}
