/******************************************
 * Auto-generated by CodeRocket
 * 21.02.2009 18:08:32
 ******************************************/
using System;
using Savchin.Core;


namespace KnowledgeBase.DAL 
{    
    
/// <summary>
/// FileStorage Value object
/// </summary>
[Serializable]
    public class FileStorageValue : ICopiable   
{
	 
     public System.Int16 FileStorageID ;
     public System.String Name ;
     public System.String Path ;
     public System.Byte SettingsID ;


         
        
        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        public void Copy(object destination)
        {
        
            FileStorageValue   dest = destination as FileStorageValue ;
            if(dest==null)
              return;
	            dest.FileStorageID = FileStorageID;
		            dest.Name = Name;
		            dest.Path = Path;
		            dest.SettingsID = SettingsID;
	            
        
        }	
        
 
        
        
             

 
	}
}
