/******************************************
 * Auto-generated by CodeRocket
 * 11.11.2008 17:09:27
 ******************************************/
using System;
using Savchin.Core;


namespace KnowledgeBase.DAL 
{    
    
/// <summary>
/// FileLink Value object
/// </summary>
[Serializable]
    public class FileLinkValue : ICopiable 
{
	 
     public System.Int32 FileLinkID ;
     public System.Int16 FileStorageID ;
     public System.String Path ;
     public System.Guid PublicID ;


         
        
        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        public void Copy(object destination)
        {
        
            FileLinkValue   dest = destination as FileLinkValue ;
            if(dest==null)
              return;
	            dest.FileLinkID = FileLinkID;
		            dest.FileStorageID = FileStorageID;
		            dest.Path = Path;
		            dest.PublicID = PublicID;
	            
        
        }	
        
 
        
        
             

 
	}
}
