/******************************************
 * Auto-generated by CodeRocket
 * 31.10.2008 23:27:40
 ******************************************/
using System;
using Savchin.Core;


namespace KnowledgeBase.DAL
{

    /// <summary>
    /// Keyword Value object
    /// </summary>
    [Serializable]
    public class KeywordValue : ICopiable
    {

        public System.DateTime CreationDate;
        public System.Int32 KeywordID;
        public System.Byte KeywordStatusID;
        public System.Int16 KeywordTypeID;
        public System.String Name;




        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        public void Copy(object destination)
        {

            KeywordValue dest = destination as KeywordValue;
            if (dest == null)
                return;
            dest.CreationDate = CreationDate;
            dest.KeywordID = KeywordID;
            dest.KeywordStatusID = KeywordStatusID;
            dest.KeywordTypeID = KeywordTypeID;
            dest.Name = Name;


        }







    }
}
