/******************************************
 * Auto-generated by CodeRocket
 * 04.11.2008 22:13:36
 ******************************************/
using System;
using Savchin.Core;


namespace KnowledgeBase.DAL
{

    /// <summary>
    /// Knowledge Value object
    /// </summary>
    [Serializable]
    public class KnowledgeValue : ICopiable
    {

        public System.Int32 CategoryID;
        public System.DateTime CreationDate;
        public System.Int32 CreatorID;
        public System.Int32 KnowledgeID;
        public System.Byte KnowledgeStatusID;
        public System.Int16 KnowledgeTypeID;
        public System.DateTime? ModificationDate;
        public System.Int32? ModificatorID;
        public System.Guid PublicID;
        public System.String Summary;
        public System.String Title;




        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        public void Copy(object destination)
        {

            KnowledgeValue dest = destination as KnowledgeValue;
            if (dest == null)
                return;
            dest.CategoryID = CategoryID;
            dest.CreationDate = CreationDate;
            dest.CreatorID = CreatorID;
            dest.KnowledgeID = KnowledgeID;
            dest.KnowledgeStatusID = KnowledgeStatusID;
            dest.KnowledgeTypeID = KnowledgeTypeID;
            dest.ModificationDate = ModificationDate;
            dest.ModificatorID = ModificatorID;
            dest.PublicID = PublicID;
            dest.Summary = Summary;
            dest.Title = Title;


        }







    }
}
