/******************************************
 * Auto-generated by CodeRocket
 * 24.11.2008 16:16:01
 ******************************************/
using System;
using Savchin.Core;


namespace KnowledgeBase.DAL
{

    /// <summary>
    /// UserFile Value object
    /// </summary>
    [Serializable]
    public class UserFileValue : ICopiable
    {

        public System.String FileName;
        public System.Int32 Size;
        public System.Int32 UserFileID;
        public System.Int32 UserID;




        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        public void Copy(object destination)
        {

            UserFileValue dest = destination as UserFileValue;
            if (dest == null)
                return;
            dest.FileName = FileName;
            dest.Size = Size;
            dest.UserFileID = UserFileID;
            dest.UserID = UserID;


        }







    }
}
