/******************************************
 * Auto-generated by CodeRocket
 * 13.10.2008 20:10:29
 ******************************************/
using System;
using Savchin.Core;


namespace KnowledgeBase.DAL
{

    /// <summary>
    /// UserRight Value object
    /// </summary>
    [Serializable]
    public class UserRightValue : ICopiable
    {

        public System.Int32 CategoryID;
        public System.Int16 PermissionID;
        public System.Int32 UserID;




        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        public void Copy(object destination)
        {

            UserRightValue dest = destination as UserRightValue;
            if (dest == null)
                return;
            dest.CategoryID = CategoryID;
            dest.PermissionID = PermissionID;
            dest.UserID = UserID;


        }







    }
}
