

/******************************************
 * Auto-generated by CodeRocket
 * 09.05.2008 10:47:06
 ******************************************/
using System;
using System.Data;
using System.Xml.Serialization;


namespace KnowledgeBase.BussinesLayer 
{    
    
	/// <summary>
	/// Base User
	/// </summary>
	[Serializable]
	public class User
{

     	
	
	 #region Properties
	 private UserValue objectValue;
        /// <summary>
        /// Gets or sets the object value.
        /// </summary>
        /// <value>The object value.</value>
        internal UserValue ObjectValue
        {
            get { return objectValue; }
            set { objectValue = value; }
        }
        
              /// <summary>
        /// Gets or sets the CreationDate.
        /// </summary>
        /// <value>The CreationDate.</value>   
		[XmlElement(ElementName = "CreationDate")]
		public System.DateTime CreationDate 
		{
			get{return objectValue.CreationDate;}
			set{objectValue.CreationDate = value;}
		}			

              /// <summary>
        /// Gets or sets the Email.
        /// </summary>
        /// <value>The Email.</value>   
		[XmlElement(ElementName = "Email")]
		public System.String Email 
		{
			get{return objectValue.Email;}
			set{objectValue.Email = value;}
		}			

              /// <summary>
        /// Gets or sets the FirstName.
        /// </summary>
        /// <value>The FirstName.</value>   
		[XmlElement(ElementName = "FirstName")]
		public System.String FirstName 
		{
			get{return objectValue.FirstName;}
			set{objectValue.FirstName = value;}
		}			

              /// <summary>
        /// Gets or sets the LastName.
        /// </summary>
        /// <value>The LastName.</value>   
		[XmlElement(ElementName = "LastName")]
		public System.String LastName 
		{
			get{return objectValue.LastName;}
			set{objectValue.LastName = value;}
		}			

              /// <summary>
        /// Gets or sets the Login.
        /// </summary>
        /// <value>The Login.</value>   
		[XmlElement(ElementName = "Login")]
		public System.String Login 
		{
			get{return objectValue.Login;}
			set{objectValue.Login = value;}
		}			

              /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        /// <value>The Password.</value>   
		[XmlElement(ElementName = "Password")]
		public System.String Password 
		{
			get{return objectValue.Password;}
			set{objectValue.Password = value;}
		}			

              /// <summary>
        /// Gets or sets the SecurityAnswer.
        /// </summary>
        /// <value>The SecurityAnswer.</value>   
		[XmlElement(ElementName = "SecurityAnswer")]
		public System.String SecurityAnswer 
		{
			get{return objectValue.SecurityAnswer;}
			set{objectValue.SecurityAnswer = value;}
		}			

              /// <summary>
        /// Gets or sets the SecurityQuestion.
        /// </summary>
        /// <value>The SecurityQuestion.</value>   
		[XmlElement(ElementName = "SecurityQuestion")]
		public System.String SecurityQuestion 
		{
			get{return objectValue.SecurityQuestion;}
			set{objectValue.SecurityQuestion = value;}
		}			

              /// <summary>
        /// Gets or sets the UserID.
        /// </summary>
        /// <value>The UserID.</value>   
		[XmlElement(ElementName = "UserID")]
		public System.Int32 UserID 
		{
			get{return objectValue.UserID;}
			set{objectValue.UserID = value;}
		}			

        
        #endregion
        
        /// <summary>
        /// Initializes a new instance of the <see cref="User"/> class.
        /// </summary>
        public User()
        {
            objectValue = new UserValue();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="User"/> class.
        /// </summary>
        /// <param name="value">The value.</param>
        internal User(UserValue value)
        {
            objectValue = value;
        }       
          
        
        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
//        protected override void Copy(object destination)
//        {
//            UserBase<TPool> dest = destination as UserBase<TPool>;
            
 //           dest._CreationDate = _CreationDate;
 //           dest._Email = _Email;
 //           dest._FirstName = _FirstName;
 //           dest._LastName = _LastName;
 //           dest._Login = _Login;
 //           dest._Password = _Password;
 //           dest._SecurityAnswer = _SecurityAnswer;
 //           dest._SecurityQuestion = _SecurityQuestion;
 //           dest._UserID = _UserID;
            
 //            base.Copy(destination);
 //       }	
        
        
        /// <summary>
        /// Validates this instance.
        /// </summary>
   //     public override void Validate()
   //     {
 //           if ( Email.Length >150|| FirstName.Length >50|| LastName.Length >50|| Login.Length >50|| Password.Length >50|| SecurityAnswer.Length >50|| SecurityQuestion.Length >50)
 //               throw new ValidateException(CommonValidationError);
 //       }	
        
        
 
 
	}
}
