/******************************************
 * Auto-generated by CodeRocket
 * 19.10.2008 16:25:58
 ******************************************/
using System;
using Savchin.Core;


namespace KnowledgeBase.DAL 
{    
    
/// <summary>
/// User Value object
/// </summary>
[Serializable]
    public class UserValue : ICopiable 
{
	 
     public System.DateTime CreationDate ;
     public System.String Email ;
     public System.String FirstName ;
     public System.Boolean IsSystem ;
     public System.Boolean IsUserAdmin ;
     public System.String LastName ;
     public System.String Login ;
     public System.String Password ;
  	 public System.Int16? RootPermissionID ; 
        public System.String SecurityAnswer ;
     public System.String SecurityQuestion ;
     public System.Int32 UserID ;


         
        
        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        public void Copy(object destination)
        {
        
            UserValue   dest = destination as UserValue ;
            if(dest==null)
              return;
	            dest.CreationDate = CreationDate;
		            dest.Email = Email;
		            dest.FirstName = FirstName;
		            dest.IsSystem = IsSystem;
		            dest.IsUserAdmin = IsUserAdmin;
		            dest.LastName = LastName;
		            dest.Login = Login;
		            dest.Password = Password;
		            dest.RootPermissionID = RootPermissionID;
		            dest.SecurityAnswer = SecurityAnswer;
		            dest.SecurityQuestion = SecurityQuestion;
		            dest.UserID = UserID;
	            
        
        }	
        
 
        
        
             

 
	}
}
