/******************************************
 * Auto-generated by CodeRocket
 * 08.11.2009 21:32:07
 ******************************************/
using System;


namespace Site.Dal.Entities 
{    
    
/// <summary>
/// License Value object
/// </summary>
[Serializable]
public class LicenseValue   
{
	 
     public System.Int32 Count ;
     public System.DateTime CreationDate ;
     public System.Int32 LicenseID ;
     public System.Int32 ProductID ;
     public System.Guid PublicKey ;
     public System.Int32 UserID ;
     public System.String Version ;
     public System.Int32 WmTransferID ;


         
        
        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        protected void Copy(object destination)
        {
        
            LicenseValue   dest = destination as LicenseValue ;
            if(dest==null)
              return;
	            dest.Count = Count;
		            dest.CreationDate = CreationDate;
		            dest.LicenseID = LicenseID;
		            dest.ProductID = ProductID;
		            dest.PublicKey = PublicKey;
		            dest.UserID = UserID;
		            dest.Version = Version;
		            dest.WmTransferID = WmTransferID;
	            
        
        }	
        
 
        
        
             

 
	}
}
