/******************************************
 * Auto-generated by CodeRocket
 * 08.11.2009 9:14:29
 ******************************************/
using System;


namespace Site.Dal.Entities
{

    /// <summary>
    /// Product Value object
    /// </summary>
    [Serializable]
    public class ProductValue
    {

        public System.DateTime CreationDate;
        public System.String Name;
        public System.Byte[] PrivateKey;
        public System.Int32 ProductID;
        public System.Byte[] PublicKey;




        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        protected void Copy(object destination)
        {

            ProductValue dest = destination as ProductValue;
            if (dest == null)
                return;
            dest.CreationDate = CreationDate;
            dest.Name = Name;
            dest.PrivateKey = PrivateKey;
            dest.ProductID = ProductID;
            dest.PublicKey = PublicKey;


        }







    }
}
