/******************************************
 * Auto-generated by CodeRocket
 * 07.11.2009 22:52:52
 ******************************************/
using System;


namespace Site.Dal.Entities
{

    /// <summary>
    /// Transfer Value object
    /// </summary>
    [Serializable]
    public class TransferValue
    {

        public System.Decimal Ammount;
        public System.DateTime Date;
        public System.String Description;
        public System.Int32 ID;
        public System.Int32? InvoiceId;
        public System.String Purse;
        public System.Int32? TransferId;




        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        protected void Copy(object destination)
        {

            TransferValue dest = destination as TransferValue;
            if (dest == null)
                return;
            dest.Ammount = Ammount;
            dest.Date = Date;
            dest.Description = Description;
            dest.ID = ID;
            dest.InvoiceId = InvoiceId;
            dest.Purse = Purse;
            dest.TransferId = TransferId;


        }







    }
}
