/******************************************
 * Auto-generated by CodeRocket
 * 08.11.2009 10:08:00
 ******************************************/
using System;


namespace Site.Dal.Entities 
{    
    
/// <summary>
/// User Value object
/// </summary>
[Serializable]
public class UserValue   
{
	 
     public System.DateTime CreationDate ;
     public System.String Email ;
     public System.String FirstName ;
     public System.Boolean IsAdmin ;
     public System.String LastName ;
     public System.String Login ;
     public System.String Password ;
     public System.String SecurityAnswer ;
     public System.String SecurityQuestion ;
     public System.Int32 UserID ;


         
        
        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        protected void Copy(object destination)
        {
        
            UserValue   dest = destination as UserValue ;
            if(dest==null)
              return;
	            dest.CreationDate = CreationDate;
		            dest.Email = Email;
		            dest.FirstName = FirstName;
		            dest.IsAdmin = IsAdmin;
		            dest.LastName = LastName;
		            dest.Login = Login;
		            dest.Password = Password;
		            dest.SecurityAnswer = SecurityAnswer;
		            dest.SecurityQuestion = SecurityQuestion;
		            dest.UserID = UserID;
	            
        
        }	
        
 
        
        
             

 
	}
}
