//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reading.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reading.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В перемешку.
        /// </summary>
        public static string DigitViewMode_All {
            get {
                return ResourceManager.GetString("DigitViewMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цифры.
        /// </summary>
        public static string DigitViewMode_Digit {
            get {
                return ResourceManager.GetString("DigitViewMode_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фигуры.
        /// </summary>
        public static string DigitViewMode_Shape {
            get {
                return ResourceManager.GetString("DigitViewMode_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string LettersTypes_All {
            get {
                return ResourceManager.GetString("LettersTypes_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Согласные.
        /// </summary>
        public static string LettersTypes_Consonants {
            get {
                return ResourceManager.GetString("LettersTypes_Consonants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гласные.
        /// </summary>
        public static string LettersTypes_Vowels {
            get {
                return ResourceManager.GetString("LettersTypes_Vowels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обратное.
        /// </summary>
        public static string PlaybackMode_Backward {
            get {
                return ResourceManager.GetString("PlaybackMode_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямое.
        /// </summary>
        public static string PlaybackMode_Forward {
            get {
                return ResourceManager.GetString("PlaybackMode_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случайное.
        /// </summary>
        public static string PlaybackMode_Random {
            get {
                return ResourceManager.GetString("PlaybackMode_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обе.
        /// </summary>
        public static string SummationMode_All {
            get {
                return ResourceManager.GetString("SummationMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вычитание.
        /// </summary>
        public static string SummationMode_Subtraction {
            get {
                return ResourceManager.GetString("SummationMode_Subtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сложение.
        /// </summary>
        public static string SummationMode_Summation {
            get {
                return ResourceManager.GetString("SummationMode_Summation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string SyllablesMode_All {
            get {
                return ResourceManager.GetString("SyllablesMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Популярные.
        /// </summary>
        public static string SyllablesMode_Popular {
            get {
                return ResourceManager.GetString("SyllablesMode_Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string SyllablesTypes_All {
            get {
                return ResourceManager.GetString("SyllablesTypes_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обратные.
        /// </summary>
        public static string SyllablesTypes_Backward {
            get {
                return ResourceManager.GetString("SyllablesTypes_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямые.
        /// </summary>
        public static string SyllablesTypes_Forward {
            get {
                return ResourceManager.GetString("SyllablesTypes_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примеры.
        /// </summary>
        public static string TableSummationMode_Questions {
            get {
                return ResourceManager.GetString("TableSummationMode_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст.
        /// </summary>
        public static string TableSummationMode_Text {
            get {
                return ResourceManager.GetString("TableSummationMode_Text", resourceCulture);
            }
        }
    }
}
