/******************************************
 * Auto-generated by CodeRocket
 * 04.02.2007 22:38:39
 ******************************************/
using System;
using System.Data;
using System.Xml.Serialization;
using WAM.BusinessLogic;

namespace WAM.Dao 
{    
    
/// <summary>
/// Categories Value object
/// </summary>
[Serializable]
public class CategoriesValue   
{
	 
     public System.Int32 CategoryID ;
     public System.String CategoryName ;
  	 public System.String? Description ; 
     	 public System.Byte[]? Picture ; 
   
         
        
        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        protected override void Copy(object destination)
        {
            CategoriesValue   dest = destination as CategoriesValue ;
            
            dest.CategoryID = CategoryID;
            dest.CategoryName = CategoryName;
            dest.Description = Description;
            dest.Picture = Picture;
            
             base.Copy(destination);
        }	
        
 
        
        
             
	    /// <summary>
	    /// Maps the IDataReader values to a Categories object
	    /// </summary>
	    /// <param name="reader">The IDataReader to map</param>
	    protected override void MapObject(IDataReader reader) 
	    {
	            int ordinal;
	
					ordinal = reader.GetOrdinal("CategoryID");
        if(!reader.IsDBNull(ordinal)) _CategoryID =((System.Int32)(reader.GetValue(ordinal)));
   	
					ordinal = reader.GetOrdinal("CategoryName");
        if(!reader.IsDBNull(ordinal)) _CategoryName =((System.String)(reader.GetValue(ordinal)));
   	
					ordinal = reader.GetOrdinal("Description");
        _Description = (!reader.IsDBNull(ordinal))?(System.String?)((System.String)(reader.GetValue(ordinal))): null;
   	
					ordinal = reader.GetOrdinal("Picture");
        _Picture = (!reader.IsDBNull(ordinal))?(System.Byte[]?)((System.Byte[])(reader.GetValue(ordinal))): null;
   		
            _ID = new IntIdentifier($pkCallingArgumets);
      }	
 
	}
}
