//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Savchin.Wpf.Controls.Fonts {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Savchin.Wpf.Controls.Fonts.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All petite caps.
        /// </summary>
        internal static string AllPetiteCaps {
            get {
                return ResourceManager.GetString("AllPetiteCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All small caps.
        /// </summary>
        internal static string AllSmallCaps {
            get {
                return ResourceManager.GetString("AllSmallCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Annotation alternates.
        /// </summary>
        internal static string AnnotationAlternates {
            get {
                return ResourceManager.GetString("AnnotationAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Capitals.
        /// </summary>
        internal static string Capitals {
            get {
                return ResourceManager.GetString("Capitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Capital spacing.
        /// </summary>
        internal static string CapitalSpacing {
            get {
                return ResourceManager.GetString("CapitalSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Case sensitive forms.
        /// </summary>
        internal static string CaseSensitiveForms {
            get {
                return ResourceManager.GetString("CaseSensitiveForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contextual alternates.
        /// </summary>
        internal static string ContextualAlternates {
            get {
                return ResourceManager.GetString("ContextualAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ligatures, contextual.
        /// </summary>
        internal static string ContextualLigatures {
            get {
                return ResourceManager.GetString("ContextualLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Swashes, contextual.
        /// </summary>
        internal static string ContextualSwashes {
            get {
                return ResourceManager.GetString("ContextualSwashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1, 2, 3, 4, 5, 6, 7, 8 ,9, 0.
        /// </summary>
        internal static string Digits {
            get {
                return ResourceManager.GetString("Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ligatures, discretionary.
        /// </summary>
        internal static string DiscretionaryLigatures {
            get {
                return ResourceManager.GetString("DiscretionaryLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на East Asian expert forms.
        /// </summary>
        internal static string EastAsianExpertForms {
            get {
                return ResourceManager.GetString("EastAsianExpertForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на East Asian language.
        /// </summary>
        internal static string EastAsianLanguage {
            get {
                return ResourceManager.GetString("EastAsianLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на East Asian widths.
        /// </summary>
        internal static string EastAsianWidths {
            get {
                return ResourceManager.GetString("EastAsianWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fraction.
        /// </summary>
        internal static string Fraction {
            get {
                return ResourceManager.GetString("Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Half.
        /// </summary>
        internal static string Half {
            get {
                return ResourceManager.GetString("Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Historical forms.
        /// </summary>
        internal static string HistoricalForms {
            get {
                return ResourceManager.GetString("HistoricalForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ligatures, historical.
        /// </summary>
        internal static string HistoricalLigatures {
            get {
                return ResourceManager.GetString("HistoricalLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hojo Kanji.
        /// </summary>
        internal static string HojoKanji {
            get {
                return ResourceManager.GetString("HojoKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inferior.
        /// </summary>
        internal static string Inferior {
            get {
                return ResourceManager.GetString("Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JIS-04.
        /// </summary>
        internal static string Jis04 {
            get {
                return ResourceManager.GetString("Jis04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JIS-78.
        /// </summary>
        internal static string Jis78 {
            get {
                return ResourceManager.GetString("Jis78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JIS-83.
        /// </summary>
        internal static string Jis83 {
            get {
                return ResourceManager.GetString("Jis83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JIS-90.
        /// </summary>
        internal static string Jis90 {
            get {
                return ResourceManager.GetString("Jis90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kerning.
        /// </summary>
        internal static string Kerning {
            get {
                return ResourceManager.GetString("Kerning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lining.
        /// </summary>
        internal static string Lining {
            get {
                return ResourceManager.GetString("Lining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mathematical Greek.
        /// </summary>
        internal static string MathematicalGreek {
            get {
                return ResourceManager.GetString("MathematicalGreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NLC Kanji.
        /// </summary>
        internal static string NlcKanji {
            get {
                return ResourceManager.GetString("NlcKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Numeral alignment.
        /// </summary>
        internal static string NumeralAlignment {
            get {
                return ResourceManager.GetString("NumeralAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Numeral style.
        /// </summary>
        internal static string NumeralStyle {
            get {
                return ResourceManager.GetString("NumeralStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old style.
        /// </summary>
        internal static string OldStyle {
            get {
                return ResourceManager.GetString("OldStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1/2.
        /// </summary>
        internal static string OneHalf {
            get {
                return ResourceManager.GetString("OneHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ordinal.
        /// </summary>
        internal static string Ordinal {
            get {
                return ResourceManager.GetString("Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Petite caps.
        /// </summary>
        internal static string PetiteCaps {
            get {
                return ResourceManager.GetString("PetiteCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proportional.
        /// </summary>
        internal static string Proportional {
            get {
                return ResourceManager.GetString("Proportional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quarter.
        /// </summary>
        internal static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ruby.
        /// </summary>
        internal static string Ruby {
            get {
                return ResourceManager.GetString("Ruby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simplified.
        /// </summary>
        internal static string Simplified {
            get {
                return ResourceManager.GetString("Simplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} (simulated).
        /// </summary>
        internal static string simulated {
            get {
                return ResourceManager.GetString("simulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slashed.
        /// </summary>
        internal static string Slashed {
            get {
                return ResourceManager.GetString("Slashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slashed zero.
        /// </summary>
        internal static string SlashedZero {
            get {
                return ResourceManager.GetString("SlashedZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Small caps.
        /// </summary>
        internal static string SmallCaps {
            get {
                return ResourceManager.GetString("SmallCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stacked.
        /// </summary>
        internal static string Stacked {
            get {
                return ResourceManager.GetString("Stacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ligatures, standard.
        /// </summary>
        internal static string StandardLigatures {
            get {
                return ResourceManager.GetString("StandardLigatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Swashes, standard.
        /// </summary>
        internal static string StandardSwashes {
            get {
                return ResourceManager.GetString("StandardSwashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic alternates.
        /// </summary>
        internal static string StylisticAlternates {
            get {
                return ResourceManager.GetString("StylisticAlternates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set  1.
        /// </summary>
        internal static string StylisticSet1 {
            get {
                return ResourceManager.GetString("StylisticSet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set 10.
        /// </summary>
        internal static string StylisticSet10 {
            get {
                return ResourceManager.GetString("StylisticSet10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set 11.
        /// </summary>
        internal static string StylisticSet11 {
            get {
                return ResourceManager.GetString("StylisticSet11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set 12.
        /// </summary>
        internal static string StylisticSet12 {
            get {
                return ResourceManager.GetString("StylisticSet12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set 13.
        /// </summary>
        internal static string StylisticSet13 {
            get {
                return ResourceManager.GetString("StylisticSet13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set 14.
        /// </summary>
        internal static string StylisticSet14 {
            get {
                return ResourceManager.GetString("StylisticSet14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set 15.
        /// </summary>
        internal static string StylisticSet15 {
            get {
                return ResourceManager.GetString("StylisticSet15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set 16.
        /// </summary>
        internal static string StylisticSet16 {
            get {
                return ResourceManager.GetString("StylisticSet16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set 17.
        /// </summary>
        internal static string StylisticSet17 {
            get {
                return ResourceManager.GetString("StylisticSet17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set 18.
        /// </summary>
        internal static string StylisticSet18 {
            get {
                return ResourceManager.GetString("StylisticSet18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set 19.
        /// </summary>
        internal static string StylisticSet19 {
            get {
                return ResourceManager.GetString("StylisticSet19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set  2.
        /// </summary>
        internal static string StylisticSet2 {
            get {
                return ResourceManager.GetString("StylisticSet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set 20.
        /// </summary>
        internal static string StylisticSet20 {
            get {
                return ResourceManager.GetString("StylisticSet20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set  3.
        /// </summary>
        internal static string StylisticSet3 {
            get {
                return ResourceManager.GetString("StylisticSet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set  4.
        /// </summary>
        internal static string StylisticSet4 {
            get {
                return ResourceManager.GetString("StylisticSet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set  5.
        /// </summary>
        internal static string StylisticSet5 {
            get {
                return ResourceManager.GetString("StylisticSet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set  6.
        /// </summary>
        internal static string StylisticSet6 {
            get {
                return ResourceManager.GetString("StylisticSet6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set  7.
        /// </summary>
        internal static string StylisticSet7 {
            get {
                return ResourceManager.GetString("StylisticSet7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set  8.
        /// </summary>
        internal static string StylisticSet8 {
            get {
                return ResourceManager.GetString("StylisticSet8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stylistic set  9.
        /// </summary>
        internal static string StylisticSet9 {
            get {
                return ResourceManager.GetString("StylisticSet9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subscript.
        /// </summary>
        internal static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Superscript.
        /// </summary>
        internal static string Superscript {
            get {
                return ResourceManager.GetString("Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tabular.
        /// </summary>
        internal static string Tabular {
            get {
                return ResourceManager.GetString("Tabular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Third.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Titling.
        /// </summary>
        internal static string Titling {
            get {
                return ResourceManager.GetString("Titling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Traditional.
        /// </summary>
        internal static string Traditional {
            get {
                return ResourceManager.GetString("Traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Traditional names.
        /// </summary>
        internal static string TraditionalNames {
            get {
                return ResourceManager.GetString("TraditionalNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unicase.
        /// </summary>
        internal static string Unicase {
            get {
                return ResourceManager.GetString("Unicase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Variants.
        /// </summary>
        internal static string Variants {
            get {
                return ResourceManager.GetString("Variants", resourceCulture);
            }
        }
    }
}
