//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prodigy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prodigy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В перемешку.
        /// </summary>
        public static string DigitViewMode_All {
            get {
                return ResourceManager.GetString("DigitViewMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цифры.
        /// </summary>
        public static string DigitViewMode_Digit {
            get {
                return ResourceManager.GetString("DigitViewMode_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фигуры.
        /// </summary>
        public static string DigitViewMode_Shape {
            get {
                return ResourceManager.GetString("DigitViewMode_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string LettersTypes_All {
            get {
                return ResourceManager.GetString("LettersTypes_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласные.
        /// </summary>
        public static string LettersTypes_Consonants {
            get {
                return ResourceManager.GetString("LettersTypes_Consonants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гласные.
        /// </summary>
        public static string LettersTypes_Vowels {
            get {
                return ResourceManager.GetString("LettersTypes_Vowels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратное.
        /// </summary>
        public static string PlaybackMode_Backward {
            get {
                return ResourceManager.GetString("PlaybackMode_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямое.
        /// </summary>
        public static string PlaybackMode_Forward {
            get {
                return ResourceManager.GetString("PlaybackMode_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случайное.
        /// </summary>
        public static string PlaybackMode_Random {
            get {
                return ResourceManager.GetString("PlaybackMode_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string SelectionMode_All {
            get {
                return ResourceManager.GetString("SelectionMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Популярные.
        /// </summary>
        public static string SelectionMode_Popular {
            get {
                return ResourceManager.GetString("SelectionMode_Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обе.
        /// </summary>
        public static string SummationMode_All {
            get {
                return ResourceManager.GetString("SummationMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вычитание.
        /// </summary>
        public static string SummationMode_Subtraction {
            get {
                return ResourceManager.GetString("SummationMode_Subtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сложение.
        /// </summary>
        public static string SummationMode_Summation {
            get {
                return ResourceManager.GetString("SummationMode_Summation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string SyllablesTypes_All {
            get {
                return ResourceManager.GetString("SyllablesTypes_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратные.
        /// </summary>
        public static string SyllablesTypes_Backward {
            get {
                return ResourceManager.GetString("SyllablesTypes_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямые.
        /// </summary>
        public static string SyllablesTypes_Forward {
            get {
                return ResourceManager.GetString("SyllablesTypes_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примеры.
        /// </summary>
        public static string TableSummationMode_Questions {
            get {
                return ResourceManager.GetString("TableSummationMode_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        public static string TableSummationMode_Text {
            get {
                return ResourceManager.GetString("TableSummationMode_Text", resourceCulture);
            }
        }
    }
}
