

/******************************************
* Auto-generated by CodeRocket
* 12.02.2008 22:01:45
******************************************/
using System;
using System.Data;
using System.Xml.Serialization;
using WAM.BusinessLogic;

namespace WAM.Dao
{

/// <summary>
  /// Base Categories
  ///
</summary>
public class CategoriesFactory
{

int odrinalCategoryID;
int odrinalCategoryName;
int odrinalDescription;


private void InitOrdinals(IDataReader reader)
{
  odrinalCategoryID= reader.GetOrdinal("CategoryID");
  odrinalCategoryName= reader.GetOrdinal("CategoryName");
  odrinalDescription= reader.GetOrdinal("Description");
}
/// <summary>
/// Maps the IDataReader values to a Categories object
///
</summary>
/// <param name="reader">The IDataReader to map</param>
protected override CategoriesValue MapObject(IDataReader reader)
{
   CategoriesValue result=new CategoriesValue();
   InitOrdinals(reader);
   


if(!reader.IsDBNull(odrinalCategoryID)) 
    result.CategoryID =((System.Int32)(reader.GetValue( odrinalCategoryID)));



if(!reader.IsDBNull(odrinalCategoryName)) 
    result.CategoryName =((System.String)(reader.GetValue( odrinalCategoryName)));



_Description = (!reader.IsDBNull(ordinal))?(System.String?)((System.String)(reader.GetValue(ordinal))): null;

  return result;
}
}
}