/******************************************
 * Auto-generated by CodeRocket
 * 12.02.2008 22:01:45
 ******************************************/
using System;
using System.Data;
using System.Xml.Serialization;

namespace WAM.Dao 
{    
    
/// <summary>
/// Categories Value object
/// </summary>
[Serializable]
public class CategoriesValue   
{
	 
     public System.Int32 CategoryID ;
     public System.String CategoryName ;
       public System.String Description ; 
   

         
        
        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        protected void Copy(object destination)
        {
        
            CategoriesValue   dest = destination as CategoriesValue ;
            if(dest==null)
              return;
	            dest.CategoryID = CategoryID;
		            dest.CategoryName = CategoryName;
		            dest.Description = Description;
	            
        
        }	
        
 
        
        
             

 
	}
}
