

/******************************************
* Auto-generated by CodeRocket
* 03.04.2008 21:55:00
******************************************/
using System;
using System.Data;
using System.Xml.Serialization;
using WAM.BusinessLogic;

namespace WAM.Dao
{

/// <summary>
  /// Base Users
  ///
</summary>
public class UsersFactory
{

int odrinalEmail;
int odrinalFirstName;
int odrinalLastName;
int odrinalLogin;
int odrinalPassword;
int odrinalUserID;


private void InitOrdinals(IDataReader reader)
{
  odrinalEmail= reader.GetOrdinal("Email");
  odrinalFirstName= reader.GetOrdinal("FirstName");
  odrinalLastName= reader.GetOrdinal("LastName");
  odrinalLogin= reader.GetOrdinal("Login");
  odrinalPassword= reader.GetOrdinal("Password");
  odrinalUserID= reader.GetOrdinal("UserID");
}
/// <summary>
/// Maps the IDataReader values to a Users object
///
</summary>
/// <param name="reader">The IDataReader to map</param>
protected override UsersValue MapObject(IDataReader reader)
{
   UsersValue result=new UsersValue();
   InitOrdinals(reader);
   


if(!reader.IsDBNull(odrinalEmail)) 
    result.Email =((System.String)(reader.GetValue( odrinalEmail)));



if(!reader.IsDBNull(odrinalFirstName)) 
    result.FirstName =((System.String)(reader.GetValue( odrinalFirstName)));



if(!reader.IsDBNull(odrinalLastName)) 
    result.LastName =((System.String)(reader.GetValue( odrinalLastName)));



if(!reader.IsDBNull(odrinalLogin)) 
    result.Login =((System.String)(reader.GetValue( odrinalLogin)));



if(!reader.IsDBNull(odrinalPassword)) 
    result.Password =((System.String)(reader.GetValue( odrinalPassword)));



if(!reader.IsDBNull(odrinalUserID)) 
    result.UserID =((System.Int32)(reader.GetValue( odrinalUserID)));

  return result;
}
}
}