/******************************************
 * Auto-generated by CodeRocket
 * 03.04.2008 21:55:00
 ******************************************/
using System;
using System.Data;
using System.Xml.Serialization;

namespace WAM.Dao 
{    
    
/// <summary>
/// Users Value object
/// </summary>
[Serializable]
public class UsersValue   
{
	 
     public System.String Email ;
     public System.String FirstName ;
     public System.String LastName ;
     public System.String Login ;
     public System.String Password ;
     public System.Int32 UserID ;


         
        
        /// <summary>
        /// Copies the specified destination.
        /// </summary>
        /// <param name="destination">The destination.</param>
        protected void Copy(object destination)
        {
        
            UsersValue   dest = destination as UsersValue ;
            if(dest==null)
              return;
	            dest.Email = Email;
		            dest.FirstName = FirstName;
		            dest.LastName = LastName;
		            dest.Login = Login;
		            dest.Password = Password;
		            dest.UserID = UserID;
	            
        
        }	
        
 
        
        
             

 
	}
}
